title: goful
menu:
  web:
    list:
      - win_msedge
      - win_chrome
      - elinks
    win_msedge:
      accel: "m"
      label: "win msedge"
      path: "msedge.exe"
    elinks:
      accel: "e"
      label: "elinks"
      path: "elinks"
    win_chrome:
      accel: "c"
      label: "win chrome"
      path: "chrome.exe"
  git:
    list:
      - add
      - commit
      - push
      - pull
      - log
      - status
    add:
      accel: "a"
      label: "add"
      path: "git add ."
    commit:
      accel: "c"
      label: "commit"
      path: "git commit -m quick"
    push:
      accel: "p"
      label: "push"
      path: "git push"
    pull:
      accel: "P"
      label: "pull"
      path: "git pull"
    log:
      accel: "l"
      label: "log"
      path: "git log"
    status:
      accel: "s"
      label: "status"
      path: "git status"
  editor:
    list:
      - separator
      - win_helix
      - win_vscode
      - win_emacs
      - win_nvim
      - win_notepad
    separator:
      accel: "-"
      label: "----win-----"
      path: ""
    win_helix:
      accel: "x"
      label: "win helix"
      path: "hx.exe %~f"
    win_vscode:
      accel: "o"
      label: "win vscode"
      path: "code-insiders %~f"
    win_emacs:
      accel: "r"
      label: "win emacs"
      path: "emacs %~f"
    win_notepad:
      accel: "t"
      label: "win notepad"
      path: "notepad %~f"
    win_nvim:
      accel: "s"
      label: "nvim"
      path: "nvim.exe %~f"
  external-command:
    list:
      - separator
      - win_helix
      - win_notepad
      - win_nvim
      - separator
      - fzf
    separator:
      accel: "-"
      label: "----win-----"
      path: ""
    win_helix:
      accel: "x"
      label: "win helix"
      path: "hx.exe %~f"
    win_notepad:
      accel: "t"
      label: "win notepad"
      path: "notepad %~f"
    win_nvim:
      accel: "s"
      label: "nvim"
      path: "nvim %~f"
    win_bat:
      accel: "b"
      label: "win bat"
      path: "bat %~f"
    fzf:
      accel: "f"
      label: "fzf"
      path: "fzf"
    bat:
      accel: "b"
      label: "bat"
      path: "bat %f"
  bookmark:
    list:
      - dropbox
      - onedrive
      - dotfiles
      - gosrc
      - workspace
      - separator
      - win_drive_d
      - win_drive_e
    separator:
      accel: "-"
      label: "------------"
      path: ""
    dropbox:
      accel: z 
      label: "~/Dropbox"
      path: "~/Dropbox"
    onedrive:
      accel: o 
      label: "~/OneDrive"
      path: "~/OneDrive"
    dotfiles:
      accel: s
      label: "~/.dotfiles"
      path: "~/.dotfiles"
    gosrc:
      accel: g
      label: "go src"
      path: "D:/gopath/src/github.com"
    workspace:
      accel: w 
      label: "D:/workspace"
      path: "D:/workspace"
    win_drive_d:
      accel: D 
      label: "D:/"
      path: "D:/"
    win_drive_e:
      accel: E 
      label: "E:/"
      path: "E:/"
