title: goful
menu:
  external-command:
    list:
      - win_notepad2
      - win_nvim-qt
    win_notepad2:
      accel: "n"
      label: "notepad2"
      path: "notepad2 %~f"
    win_nvim-qt:
      accel: "v"
      label: "nvim-qt"
      path: "nvim-qt %~f"
  bookmark:
    list:
      - dropbox
      - onedrive
      - envsetup
      - gosrc
      - workspace
      - separator
      - win_drive_f
      - win_drive_g
      - win_drive_h
    separator:
      accel: "-"
      label: "------------"
      path: ""
    dropbox:
      accel: z 
      label: "~/Dropbox"
      path: "~/Dropbox"
    onedrive:
      accel: o 
      label: "~/OneDrive"
      path: "~/OneDrive"
    envsetup:
      accel: s
      label: "~/EnvSetup"
      path: "~/EnvSetup"
    gosrc:
      accel: g
      label: "go src"
      path: "~/go/src/github.com"
    workspace:
      accel: w 
      label: "~/workspace"
      path: "~/workspace"
    win_drive_f:
      accel: F 
      label: "F:/"
      path: "F:/"
    win_drive_g:
      accel: G 
      label: "G:/"
      path: "G:/"
    win_drive_h:
      accel: H 
      label: "H:/"
      path: "H:/"
      